language: node_js
node_js:
- '6'
script: npm test
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: gBlGgaFSMPeNjy5rkN6898K1kXcZrp8p69kS+e0XBOBkJLkLY+dF6K5TGWSf1k8hsRnqWc2g6XWkm41NvUANLifeXc7tHVDHCIHJjjLNoi1jGUFtmzsH82m1PIqk8h9tnChUMBcqROtxIUKkTiAygElWJRLC9yPh5gHvJFoN20g=
  on:
    tags: true
    repo: bergie/where
